"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";

type Company={id:string;name:string;email:string|null;city:string|null};
type Campaign={id:string;name:string;subject:string;status:string;scheduledAt:string|null;createdAt:string;_count:{recipients:number};createdBy:{name:string};stats:{queued:number;sent:number;opened:number;clicked:number;bounced:number;failed:number;unsubscribed:number}};

export default function Marketing(){
 const[companies,setCompanies]=useState<Company[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[selected,setSelected]=useState<string[]>([]),[name,setName]=useState(""),[subject,setSubject]=useState(""),[html,setHtml]=useState("<p>Ciao {{nome}},</p><p>Ti contattiamo per {{azienda}}.</p>"),[scheduledAt,setScheduledAt]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);const [c,r]=await Promise.all([fetch("/api/companies?page=1&pageSize=100",{cache:"no-store"}),fetch("/api/marketing/campaigns",{cache:"no-store"})]);if(c.ok){const d=await c.json();setCompanies((d.items??[]).filter((x:Company)=>x.email))}if(r.ok)setCampaigns(await r.json());setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 async function create(){setMessage("");if(!name||!subject||!html||!selected.length){setMessage("Nome, oggetto, contenuto e almeno un destinatario sono obbligatori");return}const r=await fetch("/api/marketing/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,subject,htmlBody:html,companyIds:selected,scheduledAt:scheduledAt?new Date(scheduledAt).toISOString():undefined})});const d=await r.json();if(!r.ok){setMessage(d.error||"Errore");return}setMessage("Campagna "+d.status+" · "+d.queued+" destinatari · "+d.skipped+" esclusi");setSelected([]);setName("");setSubject("");setHtml("<p>Ciao {{nome}},</p>");setScheduledAt("");await load()}
 return <main className="min-h-screen bg-slate-100 p-5 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl"><Link href="/dashboard" className="text-sm text-slate-500">← Dashboard</Link><h1 className="mt-2 text-3xl font-bold">Email marketing</h1><p className="mt-2 text-slate-500">Campagne con segmentazione, invio asincrono, tracking e disiscrizione.</p>
 <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Nuova campagna</h2><div className="mt-4 grid gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome campagna" className="rounded-lg border p-2"/><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Oggetto" className="rounded-lg border p-2"/><textarea value={html} onChange={e=>setHtml(e.target.value)} rows={10} className="rounded-lg border p-2 font-mono text-sm"/><input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} className="rounded-lg border p-2"/><button onClick={()=>void create()} className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white">Invia / programma ({selected.length})</button>{message&&<p className="text-sm text-slate-600">{message}</p>}</div></div>
 <div className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Destinatari con email</h2><button onClick={()=>setSelected(selected.length===companies.length?[]:companies.map(c=>c.id))} className="text-sm underline">{selected.length===companies.length?"Deseleziona":"Seleziona tutti"}</button></div>{loading?<p className="mt-4 text-sm text-slate-500">Caricamento…</p>:<div className="mt-4 max-h-[500px] overflow-auto">{companies.map(c=><label key={c.id} className="flex gap-3 border-b p-3 text-sm"><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>setSelected(s=>s.includes(c.id)?s.filter(x=>x!==c.id):[...s,c.id])}/><span><b>{c.name}</b><br/><span className="text-slate-500">{c.email} · {c.city||"—"}</span></span></label>)}</div>}</div></section>
 <section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-semibold">Campagne</h2><div className="mt-3 divide-y">{campaigns.map(c=><div key={c.id} className="flex flex-wrap justify-between gap-3 py-3 text-sm"><span><b>{c.name}</b> · {c.subject}<br/><span className="text-slate-500">{c.createdBy.name} · {c._count.recipients} destinatari</span><br/><span className="text-slate-500">Inviate {c.stats.sent} · Aperte {c.stats.opened} · Click {c.stats.clicked} · Bounce {c.stats.bounced} · Fallite {c.stats.failed} · Disiscritte {c.stats.unsubscribed}</span></span><span className="rounded-full bg-slate-100 px-3 py-1">{c.status}</span></div>)}{!campaigns.length&&<p className="py-4 text-sm text-slate-500">Nessuna campagna.</p>}</div></section>
 </div></main>
}
