"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Company={id:string;name:string;category?:string|null;city?:string|null;province?:string|null;website?:string|null;email?:string|null;phone?:string|null;status:string;decisionMakerName?:string|null;confidence:number;lastVerifiedAt?:string|null};
const categories=["","Hotel","Ristorante","Pizzeria","B&B","Affittacamere","Studentato","Motel"],statuses=["","NEW","CONTACTED","QUALIFIED","OPPORTUNITY","WON","LOST"];
export default function CompaniesPage(){
 const[items,setItems]=useState<Company[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState<string[]>([]),[q,setQ]=useState(""),[city,setCity]=useState(""),[category,setCategory]=useState(""),[status,setStatus]=useState(""),[missing,setMissing]=useState(""),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[bulk,setBulk]=useState("");
 async function load(){setLoading(true);const p=new URLSearchParams({page:String(page),pageSize:"25"});if(q)p.set("q",q);if(city)p.set("city",city);if(category)p.set("category",category);if(status)p.set("status",status);if(missing)p.set("missing",missing);const r=await fetch("/api/companies?"+p,{cache:"no-store"});if(r.ok){const d=await r.json();setItems(d.items);setTotal(d.total)}setLoading(false)}
 useEffect(()=>{load()},[page,category,status,missing]); useEffect(()=>{setSelected([])},[page,category,status,missing]);
 const allPageSelected=items.length>0&&items.every(x=>selected.includes(x.id));
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
 function toggleAll(){setSelected(allPageSelected?selected.filter(id=>!items.some(x=>x.id===id)):[...new Set([...selected,...items.map(x=>x.id)])])}
 async function bulkEnrich(){if(!selected.length)return;setBulk("Avvio…");const r=await fetch("/api/enrichment/bulk",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({companyIds:selected})});const d=await r.json();setBulk(r.ok?"In coda: "+d.queued+" · saltati: "+d.skipped:(d.error||"Errore"));if(r.ok)setSelected([])}
 return <main className="min-h-screen bg-slate-100 text-slate-900"><header className="border-b bg-white px-8 py-5"><b>FleurCrm</b></header><div className="mx-auto max-w-7xl p-8">
 <div className="flex items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">CRM Lead</h1><p className="mt-2 text-slate-500">{total} aziende nel database.</p></div><Link href="/leads" className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Nuova ricerca</Link></div>
 <section className="mt-6 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-5"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(setPage(1),load())} placeholder="Cerca azienda, email, telefono..." className="rounded-lg border p-2 md:col-span-2"/><input value={city} onChange={e=>setCity(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(setPage(1),load())} placeholder="Città" className="rounded-lg border p-2"/><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}} className="rounded-lg border p-2">{categories.map(x=><option key={x} value={x}>{x||"Tutte le categorie"}</option>)}</select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="rounded-lg border p-2">{statuses.map(x=><option key={x} value={x}>{x||"Tutti gli stati"}</option>)}</select><select value={missing} onChange={e=>{setMissing(e.target.value);setPage(1)}} className="rounded-lg border p-2 md:col-span-2"><option value="">Qualsiasi completezza</option><option value="email">Senza email</option><option value="phone">Senza telefono</option><option value="website">Senza sito</option><option value="decisionMaker">Senza referente</option></select><button onClick={()=>{setPage(1);load()}} className="rounded-lg border px-4 py-2 font-semibold">Aggiorna</button></section>
 {selected.length>0&&<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-blue-50 p-4"><span className="font-semibold">{selected.length} lead selezionati</span><div className="flex items-center gap-3"><span className="text-sm text-slate-600">{bulk}</span><button onClick={bulkEnrich} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">Arricchisci selezionati</button></div></div>}
 <section className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="border-b bg-slate-50 text-left"><tr><th className="p-4"><input type="checkbox" checked={allPageSelected} onChange={toggleAll}/></th><th className="p-4">Azienda</th><th className="p-4">Categoria</th><th className="p-4">Località</th><th className="p-4">Contatti</th><th className="p-4">Referente</th><th className="p-4">Stato</th></tr></thead><tbody>{loading?<tr><td className="p-6" colSpan={7}>Caricamento...</td></tr>:items.map(c=><tr key={c.id} className="border-b last:border-0"><td className="p-4"><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>toggle(c.id)}/></td><td className="p-4"><Link href={"/companies/"+c.id} className="font-semibold hover:underline">{c.name}</Link><div className="text-xs text-slate-500">{c.website||"Sito mancante"}</div></td><td className="p-4">{c.category||"—"}</td><td className="p-4">{[c.city,c.province].filter(Boolean).join(" · ")||"—"}</td><td className="p-4"><div>{c.phone||"Telefono —"}</div><div>{c.email||"Email —"}</div></td><td className="p-4">{c.decisionMakerName||"Da arricchire"}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{c.status}</span></td></tr>)}{!loading&&items.length===0&&<tr><td className="p-8 text-center text-slate-500" colSpan={7}>Nessun lead trovato.</td></tr>}</tbody></table></section>
 <div className="mt-4 flex items-center justify-between text-sm"><span>Pagina {page} · {total} risultati</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded border bg-white px-3 py-2 disabled:opacity-40">Precedente</button><button disabled={page*25>=total} onClick={()=>setPage(p=>p+1)} className="rounded border bg-white px-3 py-2 disabled:opacity-40">Successiva</button></div></div>
 </div></main>
}