"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
type Company={id:string;name:string;category?:string|null;city?:string|null;province?:string|null;website?:string|null;email?:string|null;phone?:string|null;status:string;decisionMakerName?:string|null;confidence:number;lastVerifiedAt?:string|null};
const categories=["","Hotel","Ristorante","Pizzeria","B&B","Affittacamere","Studentato","Motel"],statuses=["","NEW","CONTACTED","QUALIFIED","OPPORTUNITY","WON","LOST"];
export default function CompaniesPage(){
 const[items,setItems]=useState<Company[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState<string[]>([]),[q,setQ]=useState(""),[city,setCity]=useState(""),[category,setCategory]=useState(""),[status,setStatus]=useState(""),[missing,setMissing]=useState(""),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[bulk,setBulk]=useState("");
 const load=useCallback(async ()=>{setLoading(true);const p=new URLSearchParams({page:String(page),pageSize:"25"});if(q)p.set("q",q);if(city)p.set("city",city);if(category)p.set("category",category);if(status)p.set("status",status);if(missing)p.set("missing",missing);const r=await fetch("/api/companies?"+p,{cache:"no-store"});if(r.ok){const d=await r.json();setItems(d.items);setTotal(d.total)}setLoading(false)},[page,q,city,category,status,missing]);
 useEffect(()=>{void load()},[load]); useEffect(()=>{setSelected([])},[page,category,status,missing]);
 const allPageSelected=items.length>0&&items.every(x=>selected.includes(x.id));
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
 function toggleAll(){setSelected(allPageSelected?selected.filter(id=>!items.some(x=>x.id===id)):[...new Set([...selected,...items.map(x=>x.id)])])}
 async function bulkEnrich(){if(!selected.length)return;setBulk("Avvio…");const r=await fetch("/api/enrichment/bulk",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({companyIds:selected})});const d=await r.json();setBulk(r.ok?"In coda: "+d.queued+" · saltati: "+d.skipped:(d.error||"Errore"));if(r.ok)setSelected([])}
 return <main className="min-h-screen bg-[#f6f7f9] text-slate-900"><header className="border-b border-slate-200 bg-white px-4 py-3 md:px-8"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-600 font-black text-white">F</div><div><b>FleurCRM</b><div className="text-[10px] uppercase tracking-widest text-slate-400">Lavanolo</div></div><nav className="ml-auto hidden gap-1 lg:flex"><Link href="/dashboard" className="rounded-lg px-3 py-2 text-xs font-semibold text-slate-500 hover:bg-slate-50">Dashboard</Link><Link href="/companies" className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Aziende</Link><Link href="/leads" className="rounded-lg px-3 py-2 text-xs font-semibold text-slate-500 hover:bg-slate-50">Lead</Link><Link href="/tasks" className="rounded-lg px-3 py-2 text-xs font-semibold text-slate-500 hover:bg-slate-50">Attività</Link><Link href="/marketing" className="rounded-lg px-3 py-2 text-xs font-semibold text-slate-500 hover:bg-slate-50">Marketing</Link></nav></div></header><div className="mx-auto max-w-7xl p-5 md:p-8">
 <div className="flex items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">CRM Lead</h1><p className="mt-2 text-slate-500">{total} aziende nel database.</p></div><Link href="/leads" className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-slate-800">Nuova ricerca</Link></div>
 <section className="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white shadow-sm p-5 md:grid-cols-5"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(setPage(1),void load())} placeholder="Cerca azienda, email, telefono..." className="rounded-xl border-slate-200 bg-white p-3 outline-none transition focus:border-emerald-400 focus:ring-4 focus:ring-emerald-50 md:col-span-2"/><input value={city} onChange={e=>setCity(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(setPage(1),load())} placeholder="Città" className="rounded-xl border-slate-200 bg-white p-3 outline-none transition focus:border-emerald-400 focus:ring-4 focus:ring-emerald-50"/><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}} className="rounded-xl border-slate-200 bg-white p-3 outline-none transition focus:border-emerald-400 focus:ring-4 focus:ring-emerald-50">{categories.map(x=><option key={x} value={x}>{x||"Tutte le categorie"}</option>)}</select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="rounded-xl border-slate-200 bg-white p-3 outline-none transition focus:border-emerald-400 focus:ring-4 focus:ring-emerald-50">{statuses.map(x=><option key={x} value={x}>{x||"Tutti gli stati"}</option>)}</select><select value={missing} onChange={e=>{setMissing(e.target.value);setPage(1)}} className="rounded-xl border-slate-200 bg-white p-3 outline-none transition focus:border-emerald-400 focus:ring-4 focus:ring-emerald-50 md:col-span-2"><option value="">Qualsiasi completezza</option><option value="email">Senza email</option><option value="phone">Senza telefono</option><option value="website">Senza sito</option><option value="decisionMaker">Senza referente</option></select><button onClick={()=>{setPage(1);load()}} className="rounded-xl border-slate-200 bg-white px-4 py-3 font-semibold transition hover:bg-slate-50">Aggiorna</button></section>
 {selected.length>0&&<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-blue-50 p-4"><span className="font-semibold">{selected.length} lead selezionati</span><div className="flex items-center gap-3"><span className="text-sm text-slate-600">{bulk}</span><button onClick={bulkEnrich} className="rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white shadow-sm hover:bg-emerald-700">Arricchisci selezionati</button></div></div>}
 <section className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="border-b border-slate-200 bg-slate-50/80 text-left"><tr><th className="p-4"><input type="checkbox" checked={allPageSelected} onChange={toggleAll}/></th><th className="p-4">Azienda</th><th className="p-4">Categoria</th><th className="p-4">Località</th><th className="p-4">Contatti</th><th className="p-4">Referente</th><th className="p-4">Stato</th></tr></thead><tbody>{loading?<tr><td className="p-6" colSpan={7}>Caricamento...</td></tr>:items.map(c=><tr key={c.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/70"><td className="p-4"><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>toggle(c.id)}/></td><td className="p-4"><Link href={"/companies/"+c.id} className="font-semibold hover:underline">{c.name}</Link><div className="text-xs text-slate-500">{c.website||"Sito mancante"}</div></td><td className="p-4">{c.category||"—"}</td><td className="p-4">{[c.city,c.province].filter(Boolean).join(" · ")||"—"}</td><td className="p-4"><div>{c.phone||"Telefono —"}</div><div>{c.email||"Email —"}</div></td><td className="p-4">{c.decisionMakerName||"Da arricchire"}</td><td className="p-4"><span className={"rounded-full px-3 py-1 text-xs font-semibold " + (c.status==="WON" ? "bg-emerald-100 text-emerald-700" : c.status==="LOST" ? "bg-red-100 text-red-700" : c.status==="OPPORTUNITY" ? "bg-violet-100 text-violet-700" : c.status==="QUALIFIED" ? "bg-blue-100 text-blue-700" : "bg-slate-100 text-slate-600")}>{c.status}</span></td></tr>)}{!loading&&items.length===0&&<tr><td className="p-8 text-center text-slate-500" colSpan={7}>Nessun lead trovato.</td></tr>}</tbody></table></section>
 <div className="mt-4 flex items-center justify-between text-sm"><span>Pagina {page} · {total} risultati</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded border bg-white px-3 py-2 disabled:opacity-40">Precedente</button><button disabled={page*25>=total} onClick={()=>setPage(p=>p+1)} className="rounded border bg-white px-3 py-2 disabled:opacity-40">Successiva</button></div></div>
 </div></main>
}